name: Deploy static files to Azure Web App - hello-world25

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy static files to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'hello-world25'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
